### ISSUE TITLE
Incompatible with Kodi 18 alpha 1?

### ISSUE THREAD

**Issue by craigcarnell** [xbmc/peripheral.joystick#67]
I installed via apt-get install on Ubuntu 16.04 and I get the add on is incompatible and has been disabled.

This is the guide to install kodi on minimalist Ubuntu: http://forum.kodi.tv/showthread.php?tid=231955

**Comment by arucard21** [comment]
As far as I can tell, Kodi 18 alpha 1 isn't released yet. It's the version set on the current master branch. So did you install through apt-get or did you compile the master branch yourself? If you did install through apt-get, from where did you get kodi? I did not see any 18.0 builds in the ubuntu repo nor the team-xbmc PPA's (both stable and nightly). 

I think this would be relevant to know in order to find out what exactly might be going wrong here.

**Comment by craigcarnell** [comment]
@arucard21 wsnipex repo

**Comment by garbear** [comment]
Version 1.2.1 has been tagged for Krypton release: https://github.com/xbmc/peripheral.joystick/releases/tag/v1.2.1

**Comment by garbear** [comment]
Can this issue be closed?

**Comment by arucard21** [comment]
> Can this issue be closed?

Given how old the issue is, the fact that the problem almost certainly has to be solved already (at least, I have this addon working on the latest Krypton release) and that there's been no response from the OP, I think this issue can be closed
